export const commandDescriptions: Record<string, string> = {
  about: "Learn more about me and my background",
  grep: "Ask me anything using AI (usage: grep [your question])",
  cd: "Change directory (just kidding, it's a fun response)",
  date: "Display the current date and time",
  echo: "Print text to the terminal",
  emacs: "Try to use the emacs editor (with a twist)",
  games: "Play interactive terminal games",
  github: "Visit my GitHub profile",
  guess: "Play a number guessing game",
  help: "Display this help menu with all available commands",
  linkedin: "Visit my LinkedIn profile",
  ls: "List directory contents (simulated)",
  mode: "Display current mode and available commands",
  move: "Play a terminal-based movement game",
  nvim: "Try to use the nvim editor (with a twist)",
  projects: "View my projects",
  quote: "Get an inspiring random quote",
  sudo: "Try to run a command with admin privileges",
  vi: "Try to use the vi editor (with a twist)",
  vim: "Try to use the vim editor (with a twist)",
  weather: "Check the weather for any city (usage: weather [city])",
  whoami: "Display the current user",
};
